// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADiFrD-NkRwVM52p2WQPqnFsZ578qZv88',
    appId: '1:745497590383:android:330e32a1a461e4529cab9a',
    messagingSenderId: '745497590383',
    projectId: 'retail-erp-dc742',
    storageBucket: 'retail-erp-dc742.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_spcW5HuAK-hMiFQ2yN-a0d9z7RCjbho',
    appId: '1:745497590383:web:f3dc32df0c1bf7699cab9a',
    messagingSenderId: '745497590383',
    projectId: 'retail-erp-dc742',
    authDomain: 'retail-erp-dc742.firebaseapp.com',
    storageBucket: 'retail-erp-dc742.firebasestorage.app',
    measurementId: 'G-DFJCMDKXQW',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_spcW5HuAK-hMiFQ2yN-a0d9z7RCjbho',
    appId: '1:745497590383:web:f3dc32df0c1bf7699cab9a',
    messagingSenderId: '745497590383',
    projectId: 'retail-erp-dc742',
    authDomain: 'retail-erp-dc742.firebaseapp.com',
    storageBucket: 'retail-erp-dc742.firebasestorage.app',
    measurementId: 'G-DFJCMDKXQW',
  );

}