import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'app_shell.dart';

Future<void> main() async {
  // Ensure bindings are initialized before calling native code.
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using options provided by FlutterFire.
  // The file `firebase_options.dart` is generated by running:
  //   dart pub global run flutterfire_cli:flutterfire configure
  // Until then, a temporary stub is present to keep analysis passing.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const ProviderScope(child: MyApp()));
}
